name: Release
on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc

      - name: Install frontend dependencies
        run: pnpm install

      - name: Get version
        id: version
        shell: pwsh
        run: |
          $version = (Get-Content "package.json" | ConvertFrom-Json).version
          echo "APP_VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Check for changesets
        id: check-changesets
        run: |
          if (Test-Path ".changeset/*.md") {
            echo "HAS_CHANGESETS=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "HAS_CHANGESETS=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Version Packages
        if: steps.check-changesets.outputs.HAS_CHANGESETS == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pnpm version-packages
          git add .
          git commit -m "chore: version packages"
          git push
        shell: pwsh

      - name: Build the app
        id: build-app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ steps.version.outputs.APP_VERSION }}
          releaseName: 'v${{ steps.version.outputs.APP_VERSION }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          packageManager: pnpm

      - name: Create Release
        id: create_release
        if: steps.build-app.outcome == 'success'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.APP_VERSION }}
          release_name: Release v${{ steps.version.outputs.APP_VERSION }}
          draft: false
          prerelease: false

      - name: Publish Release
        if: steps.build-app.outcome == 'success' && steps.create_release.outcome == 'success'
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
